// Angular/angular-firebase/src/app/app.component.ts
import { Component } from '@angular/core';
import {
  addDoc,
  Firestore,
  collection,
  getDocs,
  doc,
  updateDoc,
  deleteDoc
} from '@angular/fire/firestore'
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular-firebase';
  public data: any = []
  constructor(public firestore: Firestore) {
    this.getData()
  }
  addData(value: any) {
    const dbInstance = collection(this.firestore, 'users');
    addDoc(dbInstance, value)
      .then(() => {
        alert('Data Sent')
      })
      .catch((err) => {
        alert(err.message)
      })
  }

  getData() {
    const dbInstance = collection(this.firestore, 'users');
    getDocs(dbInstance)
      .then((response) => {
        this.data = [...response.docs.map((item) => {
          return { ...item.data(), id: item.id }
        })]
      })
  }

  updateData(id: string) {
    const dataToUpdate = doc(this.firestore, 'users', id);
    updateDoc(dataToUpdate, {
      name: 'Nishant',
      email: 'Nishant123@gmail.com'
    })
      .then(() => {
        alert('Data updated');
        this.getData()
      })
      .catch((err) => {
        alert(err.message)
      })
  }

  deleteData(id: string) {
    const dataToDelete = doc(this.firestore, 'users', id);
    deleteDoc(dataToDelete)
    .then(() => {
      alert('Data Deleted');
      this.getData()
    })
    .catch((err) => {
      alert(err.message)
    })
  }
}

<!-- <form #loginForm="ngForm" (ngSubmit)="addData(loginForm.value)">
  <div class="main">
    <div class="input-fields">
      <input name="name" ngModel placeholder="Name" id="name" type="text" class="input-field" />
    </div>
    <div class="input-fields">
      <input name="email" ngModel placeholder="Email" id="email" type="email" class="input-field" />
    </div>
    <div class="input-fields">
      <input name="password" ngModel placeholder="Password" id="password" type="password" class="input-field" />
    </div>
    <button>Add Data </button>
  </div>
</form> -->

<ul>
  <li *ngFor="let item of data">
    {{ item.email }}
    {{ item.name }}
    {{ item.password }}
    <button (click)="updateData(item.id)">
      Update
    </button>

    <button (click)="deleteData(item.id)">
      Delete
    </button>
  </li>
</ul>

// React/react-firebase/src/App.js
import './App.css';
import { useEffect, useState } from 'react';
import { app, database } from './firebaseConfig';
import {
  getAuth,
  signInWithEmailAndPassword,
  createUserWithEmailAndPassword
} from 'firebase/auth';
import {
  collection,
  addDoc,
  getDocs,
  doc,
  updateDoc, 
  deleteDoc
} from 'firebase/firestore'

function App() {
  const [array, setArray] = useState([]);
  const [data, setData] = useState({
    name: '',
    email: '',
    password: ''
  })
  const auth = getAuth();
  const dbInstance = collection(database, 'users')
  const handleInputs = (event) => {
    let inputs = { [event.target.name]: event.target.value }

    setData({ ...data, ...inputs })
  }

  const addData = () => {
    addDoc(dbInstance, data)
      .then(() => {
        alert('Data Sent')
        getData()
      })
      .catch((err) => {
        alert(err.message)
      })
  }

  const getData = async () => {
    const data = await getDocs(dbInstance);
    setArray(data.docs.map((item) => {
      return { ...item.data(), id: item.id }
    }))
  }

  const updateData = (id) => {
    let dataToUpdate = doc(database, 'users', id)
    updateDoc(dataToUpdate, {
      name: 'Ashish',
      email: 'ashishisbalh@gmail.com',
      password: 'abcdef'
    })
    .then(() => {
      alert('Data Updated')
      getData()
    })
    .catch((err) => {
      alert(err)
    })
  }

  const deleteData = (id) => {
    let dataToDelete = doc(database, 'users', id)
    deleteDoc(dataToDelete)
    .then(() => {
      alert('Data Deleted')
      getData()
    })
    .catch((err) => {
      alert(err)
    })
  }

  useEffect(() => {
    getData()
  }, [])
  return (
    <div className="App-header">
      <input
        placeholder="Name"
        name="name"
        type="text"
        className="input-fields"
        onChange={event => handleInputs(event)}
      />
      <input
        placeholder="Email"
        name="email"
        type="email"
        className="input-fields"
        onChange={event => handleInputs(event)}
      />
      <input
        placeholder="Password"
        name="password"
        type="password"
        className="input-fields"
        onChange={event => handleInputs(event)}
      />

      <button onClick={addData}>Add Data</button>

      {array.map((item) => {
        return (
          <div>
            <p>{item.name}</p>
            <p>{item.email}</p>
            <p>{item.password}</p>

            <button onClick={() => updateData(item.id)}>Update</button>
            <button onClick={() => deleteData(item.id)}>Delete</button>
            <hr />
          </div>
        )
      })}
    </div>
  );
}

export default App;
